GET http://localhost:3000/
Authorization: 5550049443b74107469df312b45d3a984a38da5ed38e0fc1b9b2899048796ce1d791adb96f22cf7ac746589548f0a3da7a42ec82e4e54bc3ebd25c55a5fea6a3

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "authorizations": "5550049443b74107469df312b45d3a984a38da5ed38e0fc1b9b2899048796ce1d791adb96f22cf7ac746589548f0a3da7a42ec82e4e54bc3ebd25c55a5fea6a3",
    "username": "abolfazlalz",
    "password": "ParisaAnd729",
    "email": "mrabolfazlalz@gmail.com",
    "firstname": "Abolfazl",
    "lastname": "Alizadeh"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "authorizations": "5550049443b74107469df312b45d3a984a38da5ed38e0fc1b9b2899048796ce1d791adb96f22cf7ac746589548f0a3da7a42ec82e4e54bc3ebd25c55a5fea6a3",
    "username": "abolfazlalz",
    "password": "ParisaAnd729"
}

### 

POST http://localhost:3000/info
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxYWVhMTU1NmFiMTY2ZTA3ZjAwZjUiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjhUMDk6MzY6MzMuMTQzWiIsImlhdCI6MTYwMTI4NjE5OH0.3wc8t0ZArDUrMSLqwRGqH0EblgJI2J-aif1KI4oWG2I"
}


###2020-09-29 8:18

POST http://localhost:3000/plan/add
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMjE0ODI0M30.sAUkdh1I_Z0fP-2sanFLHVb7Sim19eJ6GzSnfvLpvzo",
    "title": "New Title Ok",
    "description": "Just a test plan !",
    "createdDate": "2020-09-29 08:18",
    "deadlineDate": "2020-09-29 08:18"
}

###

GET http://localhost:3000/plan/get/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMjE0ODI0M30.sAUkdh1I_Z0fP-2sanFLHVb7Sim19eJ6GzSnfvLpvzo
Content-Type: application/json

###

GET http://localhost:3000/accounts/taken/username/abolfazlalz
Content-Type: application/json

###

PUT http://localhost:3000/plan/update/5f76a8c518c8744ea8115219
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMTk4NzUzM30.Mt0B0UfbBNTDe3WIjT5zwZXoIxXtNnPPekR30nRRRoE",
    "title": "Buy new CAR"
}

###

GET http://localhost:3000/plan/is-admin/5f7c7d151a33ea32c4aeff34/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMTU0MjcwN30.g4ob4Q1WQYRdFuIjJeURPZm0cF4lhY7Z7g2nH_Wuu98eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMTk4NzUzM30.Mt0B0UfbBNTDe3WIjT5zwZXoIxXtNnPPekR30nRRRoE

###

DELETE http://localhost:3000/plan/delete/5f76a8c518c8744ea8115219
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMTk4NzUzM30.Mt0B0UfbBNTDe3WIjT5zwZXoIxXtNnPPekR30nRRRoE"
}

###

POST http://localhost:3000/plan/todo/add
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczNjUyMmNlNGI0ZDMzYTRmNjJhMmMiLCJuYW1lIjoiQWJvbGZhemwiLCJsYXN0bmFtZSI6IkFsaXphZGVoIiwidXNlcm5hbWUiOiJhYm9sZmF6bGFseiIsImVtYWlsIjoibXJhYm9sZmF6bGFsekBnbWFpbC5jb20iLCJkYXRlQ3JlYXRlZCI6IjIwMjAtMDktMjlUMTY6NDc6MzAuMzk2WiIsImlhdCI6MTYwMjE0ODUzMH0.YscH1ExbKwu-o-BOS_InG1rw-8aOenrfKrOUHL6asJE",
    "planId": "5f7c7d151a33ea32c4aeff34",
    "title": "Make a lot money",
    "deadline": "2020-09-29 08:18"
}